# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 17:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('submited', models.DateField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('voters', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), blank=True, default=[], null=True, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
